server:
  port: 8003
mybatis:
  type-aliases-package: com.zhihu.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept #服务器集群，名称要一致

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&charcterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
#向注册中心注册自己,自我保护机制，宁可同时保留所有的服务，也不关闭
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-8003 #修改eureka上面的描述信息
info:
  app.name: zhihu
  company.name: test